[package]
name = "rot13"
version = "0.1.0"
authors = ["Michel Martinez <michel.martinez@linx.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
